[package]
name = "feroxripper"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.34", features = ["derive"] }
hex = "0.4.3"
ntlm-hash = "0.1.0"
regex = "1.11.1"
ring = "0.17.14"

[lib]
name = "feroxripper"
path = "src/lib.rs"
